### ISSUE TITLE
error using localhost 

### ISSUE THREAD

**Issue by seanwayland** [waylostreamers/api#1]
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:327:9)
    at new Buffer (buffer.js:283:17)
    at createUrl (file:///home/sean/Desktop/waylostreamsapi/api/index.js:10:23)
    at file:///home/sean/Desktop/waylostreamsapi/api/index.js:17:37
    at Layer.handle [as handle_request] (/home/sean/Desktop/waylostreamsapi/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sean/Desktop/waylostreamsapi/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/sean/Desktop/waylostreamsapi/api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sean/Desktop/waylostreamsapi/api/node_modules/express/lib/router/layer.js:95:5)
    at /home/sean/Desktop/waylostreamsapi/api/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/sean/Desktop/waylostreamsapi/api/node_modules/express/lib/router/index.js:335:12)

**Comment by seanwayland** [comment]
I wonder if it's the way the environment variables are set up 

echo "CF_DISTRIBUTION_BASE_URL=http://d2rzj0e9o6ddz8.cloudfront.net" > .env
if my key is "APK"
should this line look like this ?
echo "CF_ACCESS_KEY_ID=APK" >> .env
I wasnt sure if I needed to put quotes around the access key 
similarly not too sure if the url in this line needs to have quotes around it 
echo "CF_PRIVATE_KEY=$(base64 -i /home/sean/Desktop/cloudfrontkp/pk-APKAJKY4M3DMS6GO4G7Q.pem)" >> .env

**Comment by seanwayland** [comment]
I tried a few things like adding a few .toString() calls I also tried copying in my own access key into that line 
I think it's this line that is causing the issue 
**privateKeyString: new Buffer(process.env.CF_PRIVATE_KEY, 'base64').toString('utf8')**

**Comment by seanwayland** [comment]
I also tried pasting the key into the code : 
```
var key ='-----BEGIN RSA PRIVATE KEY-----' + '\n' +
    'MIIEowIBAAKCAQEApd+U5rhxtfKBP3kHCfxtA9aPOI8KN0XCoZJrTr0zAtqu7GY+'+ '\n' + ....

privateKeyString: key.toString('utf 8'),

```

Which gives this error 
Error: Invalid private key string, must include line breaks

It looks like an encoding issue
